In [ ]:
import numpy as np

temps = np.array([-5, -4, 1, 10, 16, 19, 21, 20, 14, 8, 1, -3])

days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])

month_numbers = np.arange(1, 13)

print("temps:", temps)
print("shape:", temps.shape)
print("dtype:", temps.dtype)

print("\ndays_in_month:", days_in_month)
print("shape:", days_in_month.shape)
print("dtype:", days_in_month.dtype)

print("\nmonth_numbers:", month_numbers)
print("shape:", month_numbers.shape)
print("dtype:", month_numbers.dtype)

temps: [-5 -4  1 10 16 19 21 20 14  8  1 -3]
shape: (12,)
dtype: int64

days_in_month: [31 28 31 30 31 30 31 31 30 31 30 31]
shape: (12,)
dtype: int64

month_numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,)
dtype: int64


In [ ]:
temps_f = temps * 9 / 5 + 32

print("Температура у °F:")
print(temps_f)

warm_months = temps > 15

warm_days = days_in_month[warm_months].sum()

print("\nКількість днів у році, коли середньомісячна температура > 15°C:", warm_days)

print("\nСума днів у році:", days_in_month.sum())
print("Чи дорівнює 365:", days_in_month.sum() == 365)

Температура у °F:
[23.  24.8 33.8 50.  60.8 66.2 69.8 68.  57.2 46.4 33.8 26.6]

Кількість днів у році, коли середньомісячна температура > 15°C: 123

Сума днів у році: 365
Чи дорівнює 365: True


In [ ]:
max_temp = temps.max()
max_index = temps.argmax()
max_month = month_numbers[max_index]

min_temp = temps.min()
min_index = temps.argmin()
min_month = month_numbers[min_index]

print("Найтепліший місяць:")
print("Номер місяця:", max_month)
print("Температура:", max_temp, "°C")
print("Індекс:", max_index)

print("\nНайхолодніший місяць:")
print("Номер місяця:", min_month)
print("Температура:", min_temp, "°C")
print("Індекс:", min_index)

below_zero_months = month_numbers[temps < 0]

print("\nМісяці з температурою нижче 0°C:")
print(below_zero_months)

sorted_temps = np.sort(temps)

print("\nТемператури за зростанням:")
print(sorted_temps)

print("\nОригінальний масив temps:")
print(temps)

Найтепліший місяць:
Номер місяця: 7
Температура: 21 °C
Індекс: 6

Найхолодніший місяць:
Номер місяця: 1
Температура: -5 °C
Індекс: 0

Місяці з температурою нижче 0°C:
[ 1  2 12]

Температури за зростанням:
[-5 -4 -3  1  1  8 10 14 16 19 20 21]

Оригінальний масив temps:
[-5 -4  1 10 16 19 21 20 14  8  1 -3]


In [ ]:
sun_hours = np.array([
    55, 65, 90, 140, 190, 230,
    245, 225, 165, 110, 65, 50
])

data = np.array([
    temps,
    days_in_month,
    sun_hours
])

print("Двовимірний масив:")
print(data)

print("\nФорма масиву:")
print(data.shape)

row_sums = data.sum(axis=1)

row_means = data.mean(axis=1)

print("\nСума по кожному рядку:")
print(row_sums)

print("\nСереднє по кожному рядку:")
print(row_means)

column_sums = data.sum(axis=0)

print("\nСума по кожному стовпцю:")
print(column_sums)

Двовимірний масив:
[[ -5  -4   1  10  16  19  21  20  14   8   1  -3]
 [ 31  28  31  30  31  30  31  31  30  31  30  31]
 [ 55  65  90 140 190 230 245 225 165 110  65  50]]

Форма масиву:
(3, 12)

Сума по кожному рядку:
[  98  365 1630]

Середнє по кожному рядку:
[  8.16666667  30.41666667 135.83333333]

Сума по кожному стовпцю:
[ 81  89 122 180 237 279 297 276 209 149  96  78]


In [ ]:
rows = np.array([
    temps,
    days_in_month
])

print("rows:")
print(rows)

print("\nФорма rows:", rows.shape)

correction = np.array([1, 0])

print("\ncorrection:")
print(correction)

print("Форма correction:", correction.shape)

try:
    result = rows + correction
    print(result)
except ValueError as e:
    print("\nПомилка:")
    print(e)

correction_reshaped = correction.reshape(2, 1)

print("\nНова форма correction:")
print(correction_reshaped.shape)

result = rows + correction_reshaped

print("\nРезультат rows + correction.reshape(2, 1):")
print(result)

rows:
[[-5 -4  1 10 16 19 21 20 14  8  1 -3]
 [31 28 31 30 31 30 31 31 30 31 30 31]]

Форма rows: (2, 12)

correction:
[1 0]
Форма correction: (2,)

Помилка:
operands could not be broadcast together with shapes (2,12) (2,) 

Нова форма correction:
(2, 1)

Результат rows + correction.reshape(2, 1):
[[-4 -3  2 11 17 20 22 21 15  9  2 -2]
 [31 28 31 30 31 30 31 31 30 31 30 31]]
